'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Album', [{nome: 'Album 30',
    artistaId: 30,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 1',
    artistaId: 1,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 2',
    artistaId: 2,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 3',
    artistaId: 3,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 4',
    artistaId: 4,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 5',
    artistaId: 5,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 6',
    artistaId: 6,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 7',
    artistaId: 7,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 8',
    artistaId: 8,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 9',
    artistaId: 9,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 10',
    artistaId: 10,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 11',
    artistaId: 11,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 12',
    artistaId: 12,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 13',
    artistaId: 13,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 14',
    artistaId: 14,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 15',
    artistaId: 15,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 16',
    artistaId: 16,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 17',
    artistaId: 17,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 18',
    artistaId: 18,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 19',
    artistaId: 19,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 20',
    artistaId: 20,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 21',
    artistaId: 21,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 22',
    artistaId: 22,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 23',
    artistaId: 23,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 24',
    artistaId: 24,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 25',
    artistaId: 25,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 26',
    artistaId: 26,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 27',
    artistaId: 27,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 28',
    artistaId: 28,
    createdAt: new Date(),
    updatedAt: new Date()},
    {nome: 'Album 29',
    artistaId: 29,
    createdAt: new Date(),
    updatedAt: new Date()},]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Album', null, {});
  }
};
