'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Musicas', [{
      nome: 'The Reaper',
      genero: 'acao',
      dataLancamento: '30/0/2030',
artistaId: '30',
albumId: '30',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Post to Be',
      genero: 'romance',
      dataLancamento: '1/1/201',
artistaId: '1',
albumId: '1',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Ghost',
      genero: 'drama',
      dataLancamento: '2/2/202',
artistaId: '2',
albumId: '2',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Naked',
      genero: 'terror',
      dataLancamento: '3/3/203',
artistaId: '3',
albumId: '3',
createdAt: new Date(),
updatedAt: new Date()},

    {
      nome: '6/8',
      genero: 'comedia',
      dataLancamento: '4/4/204',
artistaId: '4',
albumId: '4',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'The Cure',
      genero: 'acao',
      dataLancamento: '5/5/205',
artistaId: '5',
albumId: '5',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Fight Night',
      genero: 'romance',
      dataLancamento: '6/6/206',
artistaId: '6',
albumId: '6',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'When I Come Around',
      genero: 'drama',
      dataLancamento: '7/7/207',
artistaId: '7',
albumId: '7',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Spirit In The Sky',
      genero: 'terror',
      dataLancamento: '8/8/208',
artistaId: '8',
albumId: '8',
createdAt: new Date(),
updatedAt: new Date()},

    {
      nome: 'The High Road',
      genero: 'comedia',
      dataLancamento: '9/9/209',
artistaId: '9',
albumId: '9',
createdAt: new Date(),
updatedAt: new Date()},

    {
      nome: 'My Hero',
      genero: 'acao',
      dataLancamento: '10/10/2010',
artistaId: '10',
albumId: '10',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Peaches',
      genero: 'romance Faso',
      dataLancamento: '11/11/2011',
artistaId: '11',
albumId: '11',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: '6/8',
      genero: 'drama',
      dataLancamento: '12/12/2012',
artistaId: '12',
albumId: '12',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Wolves',
      genero: 'terror',
      dataLancamento: '13/13/2013',
artistaId: '13',
albumId: '13',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Swang',
      genero: 'comedia',
      dataLancamento: '14/14/2014',
artistaId: '14',
albumId: '14',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Lift Me Up',
      genero: 'acao ',
      dataLancamento: '15/15/2015',
artistaId: '15',
albumId: '15',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Roll Away Your Stone',
      genero: 'romance',
      dataLancamento: '16/16/2016',
artistaId: '16',
albumId: '16',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Gold',
      genero: 'drama',
      dataLancamento: '17/17/2017',
artistaId: '17',
albumId: '17',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Time is Running Out',
      genero: 'terror',
      dataLancamento: '18/18/2018',
artistaId: '18',
albumId: '18',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Good Life',
      genero: 'comedia',
      dataLancamento: '19/19/2019',
artistaId: '19',
albumId: '19',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Thunder',
      genero: 'drama',
      dataLancamento: '20/20/2020',
artistaId: '20',
albumId: '20',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Home',
      genero: 'acao',
      dataLancamento: '21/21/2021',
artistaId: '21',
albumId: '21',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Take A Look Around',
      genero: 'romance',
      dataLancamento: '22/22/2022',
artistaId: '22',
albumId: '22',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Sexual',
      genero: 'terror',
      dataLancamento: '23/23/2023',
artistaId: '23',
albumId: '23',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Another One',
      genero: 'comedia',
      dataLancamento: '24/24/2024',
artistaId: '24',
albumId: '24',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'The Boys Are Back In Town',
      genero: 'acao',
      dataLancamento: '25/25/2025',
artistaId: '25',
albumId: '25',
createdAt: new Date(),
updatedAt: new Date()},

    {
      nome: 'Born To Be Wild',
      genero: 'romance',
      dataLancamento: '26/26/2026',
artistaId: '26',
albumId: '26',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'I Owe You This',
      genero: 'drama',
      dataLancamento: '27/27/2027',
artistaId: '27',
albumId: '27',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'With Arms Wide Open',
      genero: 'terror',
      dataLancamento: '28/28/2028',
artistaId: '28',
albumId: '28',
createdAt: new Date(),
updatedAt: new Date()},
    {
      nome: 'Enemies',
      genero: 'comedia',
      dataLancamento: '29/29/2029',
artistaId: '29',
albumId: '29',
createdAt: new Date(),
updatedAt: new Date()}
   ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Musicas', null, {});
  }
};
